### ISSUE TITLE
Accelerations data not recorded

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-ios#12]
Were accelerations correctly recorded in your tests @pragmaware ?
In my case they result as the following:

![image](https://user-images.githubusercontent.com/571129/65324802-89d87400-dbad-11e9-93b9-0cd862c40443.png)

**Comment by pragmaware** [comment]
You're right, acceleration data is missing. That's because I'm not sure how to really store it.
Acceleration is a highly variable parameter. When a person is moving it can change even several times per second. So the record lists will be mostly acceleration data with repeating "weight" of the other data that is unchanging: a huge waste. On the other side, I'm not sure if calculating some kind of average over a period of time makes sense. How do you use the acceleration data?

**Comment by giohappy** [comment]
They're being used to characterize tracks and do ML analysis on (labelled)
tracks.
I haven't verified how this is managed in the Android app, did you give it
a look?

Il giorno ven 20 set 2019 alle ore 16:41 Szymon Tomasz Stefanek <
notifications@github.com> ha scritto:

**Comment by pragmaware** [comment]
I have looked again at the android app. The acceleration data is simply stored with the current event but doesn't generate events by itself. Unless I'm wrong, the very minimum interval hardcoded in the source is 1 second. With such a low frequency all one can do is figure out the orientation of the device with respect to the ground. Anyway, I added acceleration data in the same way.

**Comment by giohappy** [comment]
fixed in https://github.com/geosolutions-it/smb-ios/commit/be37776db4accfed7b79818d0d737457046b4300
